Promise.any([
	new Promise((resolve, reject) => setTimeout(() => reject(new Error("Ouch!")), 1000)),
	new Promise((resolve, reject) => setTimeout(() => reject(new Error("Error!")), 2000))
]).catch(error => {
	console.log(error.errors[0]); // Error: Ouch!
	console.log(error.errors[1]); // Error: Error 
}); 

