async function f() {
	try {
		let response = await fetch('/no-user-here');
		let user = await response.json(); 
	} catch(err) {
		// catches errors both in fetch and response.json
		alert(err); 
	}
}

f(); 

